version: "3.3"
services:



  kapua-chronix:
    hostname: kapua-chronix
    container_name: kapua-chronix
    image: 'hurence/chronix:latest'
   # network_mode: host
    ports:
      - '8983:8983'
    networks:
      - itnet

  kapua-elasticsearch:
    hostname: kapua-elasticsearch
    container_name: kapua-elasticsearch
   # network_mode: host
    command: /bin/bash bin/es-docker
    environment:
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - bootstrap.memory_lock=false
      - cluster.name=kapua-datastore
      - discovery.type=single-node
      - network.publish_host=0.0.0.0
      - transport.host=_site_
      - transport.ping_schedule=-1
      - transport.tcp.connect_timeout=30s
      - xpack.security.enabled=false
      - xpack.watcher.enabled=false
    image: 'docker.elastic.co/elasticsearch/elasticsearch:5.4.0'
    ports:
      - '9200:9200'
      - '9300:9300'
    networks:
      - itnet

  kapua-sql:
    hostname: kapua-sql
    container_name: kapua-sql
    image: 'kapua/kapua-sql:0.3.2'
   # network_mode: host
    ports:
      - '3306:3306'
      - '8181:8181'
      #- '8778:8778'
    networks:
      - itnet


  kapua-broker:
    image: 'kapua/kapua-broker:0.3.2'
    links:
      - kapua-sql:db
      - kapua-elasticsearch:es
    environment:
      - commons.db.schema.update=true
    ports:
      - 1883:1883
      - 61614:61614


  kapua-console:
    environment:
      - commons.db.schema.update=true
    image: 'kapua/kapua-console:0.3.2'
    links:
      - 'kapua-sql:db'
      - 'kapua-elasticsearch:es'
      - 'kapua-broker:broker'
   # net: host
    ports:
      - '8080:8080'
      - '8778:8778'
    networks:
      - itnet
    depends_on:
      - kapua-sql
      - kapua-elasticsearch
      - kapua-broker



  kapua-logisland:
    #command: /bin/bash bin/logisland.sh --conf conf/mqtt-to-historian.yml
    command: tail -f bin/logisland.sh
    environment:
      - MQTT_BROKER_URL=tcp://51.15.164.141:1883

    hostname: kapua-logisland
    container_name: kapua-logisland
    image: 'hurence/logisland:0.12.0'
   # network_mode: host
    ports:
      - '4050:4050'
      - '8008:8008'
    volumes:
      - ./conf/logisland:/conf
      - ./data/logisland:/data
    networks:
      - itnet

networks:
  itnet: