# Zookeeper container 172.17.0.1
zookeeper:
  image: hurence/zookeeper
  hostname: zookeeper
  container_name: zookeeper
  ports:
    - "2181:2181"

# Kafka container
kafka:
  image: hurence/kafka
  hostname: kafka
  container_name: kafka
  links:
    - zookeeper
  ports:
    - "9092:9092"
  environment:
    KAFKA_ADVERTISED_PORT: 9092
    KAFKA_ADVERTISED_HOST_NAME: sandbox
    KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    KAFKA_JMX_PORT: 7071

# ES container    
elasticsearch:
  environment:
    - ES_JAVA_OPT="-Xms1G -Xmx1G"
    - cluster.name=es-logisland
    - http.host=0.0.0.0
    - transport.host=0.0.0.0
    - xpack.security.enabled=false
  hostname: elasticsearch
  container_name: elasticsearch
  image: 'docker.elastic.co/elasticsearch/elasticsearch:5.4.0'
  ports:
    - '9200:9200'
    - '9300:9300'

# Kibana container    
kibana: 
  environment:
    - 'ELASTICSEARCH_URL=http://elasticsearch:9200'
  image: 'docker.elastic.co/kibana/kibana:5.4.0'
  container_name: kibana
  links:
    - elasticsearch
  ports:
    - '5601:5601'    

# Logisland container : does nothing but launching
logisland:
  image: hurence/logisland
  command: tail -f bin/logisland.sh
  #command: bin/logisland.sh --conf /conf/index-apache-logs.yml
  links:
    - zookeeper
    - kafka
    - elasticsearch
#   - spark-master
#   - spark-worker
  ports:
    - "4050:4050"
  volumes:
    - ./conf/logisland:/conf
    - ./data/logisland:/data
  container_name: logisland
  extra_hosts:
    - "sandbox:172.17.0.1"


#hbase:
#    image: adaminspace/hbase
#    container_name: hbase
  # Override hbase-site.xml before starting HBase to redirect zookeeper connection to zookeeper hosted in logisland docker container.
#    command: /bin/sh -c 'cat /data/hbase/hbase-site.xml > /usr/local/hbase/hbase-1.1.2/conf/hbase-site.xml && hbase master start'
#    environment:
    # Prevent HBase to start its own zookeeper.
#     - HBASE_MANAGES_ZK=false
#   volumes:
    # /data/webanalytics/hbase/run-command.sh is used to send non-interactive commands to HBase.
#    - ./data:/data

#spark-master:
#    image: hurence/spark
#    command: bin/spark-class org.apache.spark.deploy.master.Master -h spark-master
#    hostname: spark-master
#    environment:
#      MASTER: spark://spark-master:7077
#      SPARK_CONF_DIR: /conf
#      SPARK_PUBLIC_DNS: sandbox
#    expose:
#      - 7001
#      - 7002
#      - 7003
#      - 7004
#      - 7005
#      - 7006
#      - 7077
#      - 6066
#    ports:
#      - 6066:6066
#      - 7077:7077
#      - 8080:8080
#    volumes:
#      - ./conf/spark-master:/conf
#      - ./data:/tmp/data



#spark-worker:
#    image: hurence/spark
#    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
#    hostname: spark-worker
#    environment:
#      SPARK_CONF_DIR: /conf
#      SPARK_PUBLIC_DNS: sandbox
#      SPARK_WORKER_CORES: 4
#      SPARK_WORKER_MEMORY: 4g
#      SPARK_WORKER_PORT: 8881
#      SPARK_WORKER_WEBUI_PORT: 8081
#    links:
#      - spark-master
#    expose:
#      - 7012
#      - 7013
#      - 7014
#      - 7015
#      - 7016
#      - 8881
#    ports:
#      - 8081:8081
#    volumes:
#      - ./conf/spark-worker-1:/conf
#      - ./data:/tmp/data

